from enum import Enum

class State(Enum):
    START = "START"
    ASK_ACCOUNT_ID = "ASK_ACCOUNT_ID"
    VERIFY_NAME = "VERIFY_NAME"
    VERIFY_SECONDARY = "VERIFY_SECONDARY"
    SHOW_BALANCE = "SHOW_BALANCE"
    COLLECT_AMOUNT = "COLLECT_AMOUNT"
    CARD_NUMBER = "CARD_NUMBER"
    CARD_NAME = "CARD_NAME"
    CARD_CVV = "CARD_CVV"
    CARD_EXPIRY = "CARD_EXPIRY"
    PROCESS_PAYMENT = "PROCESS_PAYMENT"
    COMPLETE = "COMPLETE"
    END = "END"